cangelog:
  exclude:
    labels:
      - repo-admin
    authors:
      - rptools-automation
  categories:
    - title: Breaking Changes :bomb:
      labels:
        - breaking-change
    - title: New Features :partying_face:
      labels:
        - feature
    - title: Performance Improvements :racing_car:
      labels:
        - performance
    - title: Bug Fixes :adhesive_bandage:	
      labels:
        - bug
    - title: Other Changes :thought_balloon:
      labels:
        - "*"
  